version: "3"
services:
  python:
    build: ./
    image: atcoder
    container_name: atcoder
    environment:
      - ATCODER_REVEL_SESSION=${ATCODER_REVEL_SESSION}
    tty: true
    volumes: 
      - ../../atcoder_python:/atcoder_python
    